{{- if .Values.secretData }}
{{- template "common.secret" (list . "floe.secret") -}}
{{- end }}
{{- define "floe.secret" -}}
data:
  {{- range $k, $v := .Values.secretData }}
  {{ $k }}: {{ toString $v | b64enc | quote }}
  {{- end }}
{{- end -}}
